// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1hko8AU9kBeQ_nCsawtEWmioeaB6KoCw',
    appId: '1:479989048019:web:bbdf74d2a8f70722c12a26',
    messagingSenderId: '479989048019',
    projectId: 'smart-home-ce704',
    authDomain: 'smart-home-ce704.firebaseapp.com',
    storageBucket: 'smart-home-ce704.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRGZTmPsomUQLcKYI9bG3Yc1S2UGFLJ8s',
    appId: '1:479989048019:android:1ab6df10a8f36ebdc12a26',
    messagingSenderId: '479989048019',
    projectId: 'smart-home-ce704',
    storageBucket: 'smart-home-ce704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjl0xl7E3vgYndHXlx0r2-p3_M5NTzk3o',
    appId: '1:479989048019:ios:89ef0fe79b7f4b43c12a26',
    messagingSenderId: '479989048019',
    projectId: 'smart-home-ce704',
    storageBucket: 'smart-home-ce704.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );
}
